
CREATE TABLE casbin_rule
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ptype VARCHAR(100)                             NOT NULL,
    v0    VARCHAR(100),
    v1    VARCHAR(100),
    v2    VARCHAR(100),
    v3    VARCHAR(100),
    v4    VARCHAR(100),
    v5    VARCHAR(100),
    CONSTRAINT pk_casbin_rule PRIMARY KEY (id)
);

CREATE TABLE category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(100)                            NOT NULL,
    updated_by  VARCHAR(100),
    status      VARCHAR(255)                            NOT NULL,
    name        VARCHAR(50)                             NOT NULL,
    description VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE item
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(100)                            NOT NULL,
    updated_by    VARCHAR(100),
    status        VARCHAR(255)                            NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    stock         INTEGER                                 NOT NULL,
    minimum_stock INTEGER                                 NOT NULL,
    unit          VARCHAR(255)                            NOT NULL,
    type          VARCHAR(255)                            NOT NULL,
    category_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE logs
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(100)                            NOT NULL,
    updated_by VARCHAR(100),
    status     VARCHAR(255)                            NOT NULL,
    comment    VARCHAR(1000)                           NOT NULL,
    date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_logs PRIMARY KEY (id)
);

CREATE TABLE role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(100)                            NOT NULL,
    updated_by VARCHAR(100),
    status     VARCHAR(255)                            NOT NULL,
    role       VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE user_torre
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(100)                            NOT NULL,
    updated_by VARCHAR(100),
    status     VARCHAR(255)                            NOT NULL,
    username   VARCHAR(100)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    name       VARCHAR(200)                            NOT NULL,
    lastname   VARCHAR(200)                            NOT NULL,
    cellphone  INTEGER                                 NOT NULL,
    email      VARCHAR(200)                            NOT NULL,
    role_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_torre PRIMARY KEY (id),
    CONSTRAINT FK_USER_TORRE_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id)
);

ALTER TABLE user_torre
    ADD CONSTRAINT uc_user_torre_username UNIQUE (username);

ALTER TABLE item
    ADD CONSTRAINT FK_ITEM_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE logs
    ADD CONSTRAINT FK_LOGS_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

ALTER TABLE logs
    ADD CONSTRAINT FK_LOGS_ON_USER FOREIGN KEY (user_id) REFERENCES user_torre (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES user_torre (id);